services:
  - type: web
    name: best-shop-api
    env: python

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: WEBAPP_URL
        sync: false

      - key: DATABASE_URL
        value: sqlite:///./best_shop.db